[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Headers = "X-Requested-With, x-application-version, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding, DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,X-Application-Version,X-SNJS-Version'"
