[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Headers = "X-Requested-With, x-application-version, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding"
